# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-23 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountname', models.CharField(max_length=30)),
                ('accountmanager', models.CharField(max_length=100)),
                ('accountwork', models.CharField(max_length=50, null=True)),
                ('accounttype', models.CharField(max_length=50, null=True)),
                ('accountnum', models.CharField(max_length=30)),
                ('accountaddress', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
