# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-13 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='num',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
