# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-17 01:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('design_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=25, null=True)),
                ('code', models.CharField(max_length=25, null=True)),
                ('buyer', models.CharField(max_length=10, null=True)),
                ('type', models.IntegerField(null=True)),
                ('state', models.IntegerField(default=0, null=True)),
                ('order_date', models.DateTimeField(null=True)),
                ('due_date', models.DateTimeField(null=True)),
                ('order_round', models.IntegerField(default=1, null=True)),
                ('order_inout', models.IntegerField(default=0, null=True)),
                ('cheack', models.BooleanField(default=False)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Fabric_Order',
            },
        ),
        migrations.CreateModel(
            name='Order_DesignData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25, null=True)),
                ('design_qty', models.IntegerField(null=True)),
                ('qr_code', models.ImageField(null=True, upload_to='')),
                ('design_data_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design_data.FSTY_CAD_Design_Data')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
            options={
                'db_table': 'Fabric_Order_DesignData',
            },
        ),
    ]
