# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-12-01 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20201201_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='style_order',
            name='factory_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
