# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-17 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Knit_Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tns_code', models.CharField(max_length=50, null=True)),
                ('user_id', models.CharField(max_length=50, null=True)),
                ('company_code', models.CharField(max_length=50, null=True)),
                ('trs_installation_time', models.DateTimeField(null=True)),
                ('trs_model_name', models.CharField(max_length=50, null=True)),
                ('trs_beam_cnt', models.IntegerField(null=True)),
                ('trs_bar_cnt', models.IntegerField(null=True)),
                ('trs_rpm_main', models.IntegerField(null=True)),
                ('trs_eac_enable', models.IntegerField(null=True)),
                ('trs_tempo', models.IntegerField(null=True)),
                ('trs_lowmotor_enable', models.IntegerField(null=True)),
                ('trs_gauge', models.IntegerField(null=True)),
                ('trs_ip', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'Knit_Machine',
            },
        ),
        migrations.CreateModel(
            name='Warp_Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tns_code', models.CharField(max_length=50, null=True)),
                ('user_id', models.CharField(max_length=50, null=True)),
                ('company_code', models.CharField(max_length=50, null=True)),
                ('tws_name', models.CharField(max_length=50, null=True)),
                ('tws_installation_time', models.DateTimeField(null=True)),
                ('tws_ip', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'Warp_Machine',
            },
        ),
        migrations.CreateModel(
            name='YW_Knit_Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('code', models.CharField(max_length=50, null=True)),
                ('create_data', models.DateTimeField(auto_now_add=True)),
                ('rpm', models.IntegerField(null=True)),
                ('gauge', models.IntegerField(null=True)),
                ('bar_cnt', models.IntegerField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Company')),
            ],
            options={
                'db_table': 'yw_knit_machine',
            },
        ),
        migrations.CreateModel(
            name='YW_Warp_Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('code', models.CharField(max_length=50, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Company')),
            ],
            options={
                'db_table': 'yw_warp_machine',
            },
        ),
    ]
