# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-17 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('design_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('yarn_qty', models.IntegerField(default=0)),
                ('size', models.IntegerField(null=True)),
                ('Receivingdate', models.CharField(default='2020-06-17 10:59', max_length=30)),
            ],
            options={
                'db_table': 'Fabric_Beam',
            },
        ),
        migrations.CreateModel(
            name='Raw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('designData_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design_data.FSTY_CAD_Design_Data')),
            ],
            options={
                'db_table': 'Fabric_Raw',
            },
        ),
        migrations.CreateModel(
            name='RawRoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_yard', models.IntegerField(default=0)),
                ('raw_weight', models.IntegerField(default=0)),
                ('raw_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Raw')),
            ],
            options={
                'db_table': 'Fabric_RawRoll',
            },
        ),
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollname', models.CharField(max_length=25, null=True)),
                ('rollfabricname', models.CharField(max_length=30, null=True)),
                ('rollfabricdate', models.DateField(blank=True, default=None, null=True)),
                ('rolloutdate', models.DateField(blank=True, default=None, null=True)),
                ('receivingdate', models.DateTimeField(blank=True, default='2020-06-17 10:59', null=True)),
                ('rollcount', models.IntegerField()),
                ('rollfabricerror', models.IntegerField()),
                ('rollfabrictrue', models.IntegerField()),
                ('rollfabriclength', models.IntegerField()),
                ('rollfabricweight', models.IntegerField()),
            ],
            options={
                'db_table': 'Fabric_Roll',
            },
        ),
        migrations.CreateModel(
            name='Yarn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('code', models.CharField(max_length=25, null=True)),
                ('type', models.CharField(max_length=25, null=True)),
                ('maker', models.CharField(max_length=25, null=True)),
                ('count', models.IntegerField(null=True)),
                ('filament', models.IntegerField(null=True)),
                ('contraction', models.IntegerField(null=True)),
                ('material', models.CharField(max_length=10, null=True)),
                ('kind', models.CharField(max_length=25, null=True)),
                ('color', models.CharField(max_length=25, null=True)),
                ('weight', models.IntegerField(default=0)),
                ('qty', models.IntegerField(default=0)),
                ('Receivingdate', models.CharField(default='2020-06-17 10:59', max_length=30)),
            ],
            options={
                'db_table': 'Fabric_Yarn',
            },
        ),
        migrations.AddField(
            model_name='beam',
            name='yarn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.Yarn'),
        ),
    ]
