# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-11-17 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raw',
            name='input_date',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='raw',
            name='item_name',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='beam',
            name='Receivingdate',
            field=models.CharField(default='2020-11-17 16:22', max_length=30),
        ),
        migrations.AlterField(
            model_name='roll',
            name='receivingdate',
            field=models.DateTimeField(blank=True, default='2020-11-17 16:22', null=True),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='Receivingdate',
            field=models.CharField(default='2020-11-17 16:22', max_length=30),
        ),
    ]
