# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-17 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_auto_20201117_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raw',
            name='input_date',
        ),
        migrations.RemoveField(
            model_name='raw',
            name='qty',
        ),
        migrations.AlterField(
            model_name='beam',
            name='Receivingdate',
            field=models.CharField(default='2020-11-17 17:39', max_length=30),
        ),
        migrations.AlterField(
            model_name='roll',
            name='receivingdate',
            field=models.DateTimeField(blank=True, default='2020-11-17 17:39', null=True),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='Receivingdate',
            field=models.CharField(default='2020-11-17 17:39', max_length=30),
        ),
    ]
