# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-11-17 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_auto_20201117_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='raw',
            name='input_date',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='raw',
            name='qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='beam',
            name='Receivingdate',
            field=models.CharField(default='2020-11-17 19:48', max_length=30),
        ),
        migrations.AlterField(
            model_name='roll',
            name='receivingdate',
            field=models.DateTimeField(blank=True, default='2020-11-17 19:48', null=True),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='Receivingdate',
            field=models.CharField(default='2020-11-17 19:48', max_length=30),
        ),
    ]
